# Generated by Django 5.0.7 on 2024-07-22 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
